name: Build and Test .NET Web API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up .NET Core SDK
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Specify the .NET version your project uses

      # Install dependencies and restore
      - name: Restore dependencies
        run: dotnet restore

      # Build the project
      - name: Build project
        run: dotnet build --no-restore --configuration Release

      # Run tests
      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      # Publish the project (optional step for creating a build artifact)
      - name: Publish project
        run: dotnet publish -c Release -o output

      # Upload the build as an artifact (optional step for further deployment stages)
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: output
